### ISSUE TITLE
SQLite plugin needs to create directory

### ISSUE THREAD

**Issue by mitchellsimoens** [ModusCreateOrg/gimbal#116]
The sqlite3 module does not handle creating the directories to save the database file to. So if you pass in a file with a nested and nonexistent directory path like:

```yaml
plugins:
  - "@modus/gimbal-plugin-last-value"
  - plugin: "@modus/gimbal-plugin-sqlite"
    lastValue: true
    file: artifacts/gimbal_tests.db
```

The plugin will error out because it doesn't create the artifcats directory. We need to use mkdirp module to create the directory prior to initializing sqlite3.
