### ISSUE TITLE
Only outputs Asciiart and "Finished successfully". No report.

### ISSUE THREAD

**Issue by tpraxl** [ModusCreateOrg/gimbal#143]
**Describe the bug**
When running `gimbal audit` for a web project, nothing is reported.

**To Reproduce**

`npm install -g @modus/gimbal`

1. `mkdir gimbal-problem`
2. `cd gimbal-problem`
3. `mkdir build`
4. `wget https://github.com/ModusCreateOrg/gimbal/tree/master/packages/gimbal/docs/module/size -O build/index.html` (should be around 70KB)
5. `gimbal audit`

**Expected behavior**
Some kind of report. Especially since index.html busts the default size treshold of `build/index.html`.

**Screenshots**
```
$ gimbal audit 
      ___                       ___                         ___
     /\__\                     /\  \         _____         /\  \
    /:/ _/_       ___         |::\  \       /::\  \       /::\  \
   /:/ /\  \     /\__\        |:|:\  \     /:/\:\  \     /:/\:\  \
  /:/ /::\  \   /:/__/      __|:|\:\  \   /:/ /::\__\   /:/ /::\  \   ___     ___
 /:/__\/\:\__\ /::\  \     /::::|_\:\__\ /:/_/:/\:|__| /:/_/:/\:\__\ /\  \   /\__\
 \:\  \ /:/  / \/\:\  \__  \:\~~\  \/__/ \:\/:/ /:/  / \:\/:/  \/__/ \:\  \ /:/  /
  \:\  /:/  /     \:\/\__\  \:\  \        \::/_/:/  /   \::/__/       \:\  /:/  /
   \:\/:/  /       \::/  /   \:\  \        \:\/:/  /     \:\  \        \:\/:/  /
    \::/  /        /:/  /     \:\__\        \::/  /       \:\__\        \::/  /
     \/__/         \/__/       \/__/         \/__/         \/__/         \/__/

  _                 __  __               _                    ____                         _
 | |__    _   _    |  \/  |   ___     __| |  _   _   ___     / ___|  _ __    ___    __ _  | |_    ___
 | '_ \  | | | |   | |\/| |  / _ \   / _` | | | | | / __|   | |     | '__|  / _ \  / _` | | __|  / _ \
 | |_) | | |_| |   | |  | | | (_) | | (_| | | |_| | \__ \   | |___  | |    |  __/ | (_| | | |_  |  __/
 |_.__/   \__, |   |_|  |_|  \___/   \__,_|  \__,_| |___/    \____| |_|     \___|  \__,_|  \__|  \___|
          |___/
 ─────────────────────────────────────────────────────────────────────────────────────────────────────

Finished successfully
```

The same applies in an actual web project, regardless of several different configurations.

**Desktop (please complete the following information):**

- OS: Linux Mint 18.3
- Browser: chrome is present
- Version: 76.0.3809.100 (Official Build) (64-bit)

**Additional context**

```bash
$ uname -a                                     
Linux joseph 4.15.0-58-generic #64~16.04.1-Ubuntu SMP Wed Aug 7 14:10:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ node --version                            
v10.16.3
$ npm --version 
6.9.0
$  gimbal --version
      ___                       ___                         ___
     /\__\                     /\  \         _____         /\  \
    /:/ _/_       ___         |::\  \       /::\  \       /::\  \
   /:/ /\  \     /\__\        |:|:\  \     /:/\:\  \     /:/\:\  \
  /:/ /::\  \   /:/__/      __|:|\:\  \   /:/ /::\__\   /:/ /::\  \   ___     ___
 /:/__\/\:\__\ /::\  \     /::::|_\:\__\ /:/_/:/\:|__| /:/_/:/\:\__\ /\  \   /\__\
 \:\  \ /:/  / \/\:\  \__  \:\~~\  \/__/ \:\/:/ /:/  / \:\/:/  \/__/ \:\  \ /:/  /
  \:\  /:/  /     \:\/\__\  \:\  \        \::/_/:/  /   \::/__/       \:\  /:/  /
   \:\/:/  /       \::/  /   \:\  \        \:\/:/  /     \:\  \        \:\/:/  /
    \::/  /        /:/  /     \:\__\        \::/  /       \:\__\        \::/  /
     \/__/         \/__/       \/__/         \/__/         \/__/         \/__/

  _                 __  __               _                    ____                         _
 | |__    _   _    |  \/  |   ___     __| |  _   _   ___     / ___|  _ __    ___    __ _  | |_    ___
 | '_ \  | | | |   | |\/| |  / _ \   / _` | | | | | / __|   | |     | '__|  / _ \  / _` | | __|  / _ \
 | |_) | | |_| |   | |  | | | (_) | | (_| | | |_| | \__ \   | |___  | |    |  __/ | (_| | | |_  |  __/
 |_.__/   \__, |   |_|  |_|  \___/   \__,_|  \__,_| |___/    \____| |_|     \___|  \__,_|  \__|  \___|
          |___/
 ─────────────────────────────────────────────────────────────────────────────────────────────────────

1.1.14
$ lighthouse --version                                                                                                                                                                 
5.2.0
```

**Comment by grgur** [comment]
Thanks for creating this issue @tpraxl 
What's the path to your application sources? e.g. `src/` or `app/` or something else?
If you have a [`gimbalrc`](https://github.com/ModusCreateOrg/gimbal/tree/master/packages/gimbal/docs/config) file, can you post it here?

**Comment by tpraxl** [comment]
In the use case above, it was `build/`. Please try to reproduce it as described. Maybe your system yields another result and that would lead us on the right track. 

In the other project, I had it all:

* no config
* a `.gimbalrc.yml`
* a `.gimbalrc.yml` and `gimbal --config=.gimbalrc.yml audit`
* build directory named `public` and configured using
  * `gimbal audit --build-dir public`
  * yml (see below)
* a copy of that public directory named `build`

I tested both .gimbalrc.yml files:

Your example:

```yml
configs:
  heap-snapshot:
    threshold:
      Documents: 5
      Frames: 2
      JSHeapTotalSize: 23356000
      JSHeapUsedSize: 15068000
      Nodes: 800
      RecalcStyleCount: 9
  lighthouse:
    threshold:
      accessibility: 93
      'best-practices': 90
      performance: 50
      pwa: 75
      seo: 100
  size:
    - path: ./build/precache-*.js
      maxSize: 500 B
    - path: ./build/static/js/*.chunk.js
      maxSize: 1 MB
    - path: ./build/static/js/runtime*.js
      maxSize: 10 KB
    - path: ./build/
      maxSize: 1 B
```

and a custom file (the exact configuration changed massively during testing):

```yml
configs:
  puppeteer:
    headless: true
  lighthouse:
    outputHtml: reports/lighthouse.html
    treshold:
        accessibility: 100
        'best-practices': 100
        performance: 100
        pwa: 100
        sweo: 100
  size:
    treshold:
      - path: ./public/css/
        maxSize: 1 B
      - path: ./public/js/
        maxSize: 1 B
      - path: ./public/
        maxSize: 2 B
  unused-source:
    treshold:
      - path: public/css/
        type: css
        maxSize: 25%
      - path: public/js/
        type: js
        maxSize: 25%
  outputs:
    html: ./reports/gimbal.html
    json: ./reports/gimbal.json
    markdown: ./reports/gimbal.md
  jobs:
    - audit
```
