### ISSUE TITLE
v2 Idea Collection

### ISSUE THREAD

**Issue by mitchellsimoens** [ModusCreateOrg/gimbal#158]
I'll do my best keeping a running list of what we want to add, change, remove from v1 in a v2 release. We are wanting to collect what people love about gimbal, what they dislike, what they hate, what they want from a tool like gimbal. There is no piece of feedback that we aren't wanting regardless if it's good or bad feedback. The more you give us, the more we can do to address them!

**Comment by mitchellsimoens** [comment]
v1 uses a static server to host the build of the application. This is a great option till you get into more complex scenarios. Client project I'm on right now has some calls to the server made at the start of an application but these will fail because there is no server. I need a way for my CI process to startup the backend and frontend and gimbal be able to run audits against a URL I pass to gimbal.

In the same vein, it'd be great if the browser audits could be run on any remote web site. Not saying this is how it should work but running `gimbal --url github.com` should run browser audits against github.com. There are some audits that wouldn't run like the size and source map explorer since they are run against local files and that's fine.

**Comment by mitchellsimoens** [comment]
I love the config file but as things have changed, the format of the config file is weird and should be looked at.

For example, the builtin audits, to set thresholds you put them in the `configs` object but then you can set which audits you want in the separate `audits` array. This is an example:

```yaml
audits:
  - size

configs:
  size:
    thresholds:
      foo.js: 1 KB
```

This isn't necessarily bad but when we added plugins, you set the threshold for that plugin within that plugin object like so:

```yaml
audits:
  - axe

plugins:
  - plugin: '@modus/gimbal-plugin-axe'
    thresholds:
      bypass: serious
```

Once again, this isn't bad but it made me think, should we do the same thing we are doing in the plugins object in the audits array (or make audits an object):

```yaml
audits:
  axe:
    thresholds:
      bypass: serious
  size:
    thresholds:
      foo.js: 1 KB
```

plugins can still have objects since they may have options (and the ones we supply do) but thresholds seem to go better in the audits and it's one place for them.
