### ISSUE TITLE
Github Comment not appearing

### ISSUE THREAD

**Issue by camposcristianeze** [ModusCreateOrg/gimbal#163]
**Describe the bug**
For some reason, the comment in the PR of github is not appearing
**To Reproduce**

1. Created the workflow
2. Set the .yml config file with the verbose log
3. Execute the workflow after a commit 

**Expected behavior**
Log said that comment should appear but for some reason is not on the PR.

**Screenshots**
![image](https://user-images.githubusercontent.com/1928706/79304993-821d4b80-7ec0-11ea-9fc9-78d608fede95.png)

**Additional context**
Logs with verbose comments:
```
├────────────────────────────────────────────────────────┼───────────┼───────────┼─────────┤
│ SEO                                                    │    90     │    90     │    ✓    │
├────────────────────────────────────────────────────────┼───────────┼───────────┼─────────┤
│ Progressive Web App                                    │    52     │    52     │    ✓    │
└────────────────────────────────────────────────────────┴───────────┴───────────┴─────────┘
HTML report written to: /github/workspace/gimbal-artifacts/results.html
JSON report written to: /github/workspace/gimbal-artifacts/results.json
Markdown report written to: /github/workspace/gimbal-artifacts/results.md
gimbal/vcs/comment [2020-04-15T06:20:55.378Z] Detected CI: GitHubActions
gimbal/vcs/comment [2020-04-15T06:20:55.390Z] Detected VCS: GitHub
gimbal/vcs/comment [2020-04-15T06:20:55.405Z] Commenting on VCS...
```

**Comment by grgur** [comment]
Hi @camposcristianeze, thanks for that question.
Do you have `GITHUB_AUTH_TOKEN` environmental variable in you CI settings? The value should be the personal token (GitHub) for a user that has privileges to comment on the project.

**Comment by camposcristianeze** [comment]
Thanks for the answer @grgur . Realised that the comments were working, but they are appearing as commit comments. Any way to add them as comments on a PR instead?

![image](https://user-images.githubusercontent.com/1928706/80153684-04c29c80-858c-11ea-911c-b8ef724bdb7f.png)


This is our current action:

```
name: Pull Request Deploy
on:
  pull_request:
    branches:
      - staging
      - master
jobs:
gimbal:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install yarn dependencies
        run: yarn
      - name: Build
        env:
          CI: ''
        run: yarn build
      - name: Performance Budgeting Regression Testing
        uses: ModusCreateOrg/gimbal/action@master
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GIMBAL_GITHUB_TOKEN }}
```

**Comment by mitchellsimoens** [comment]
As of when the last publish of gimbal, GitHub actions does not provide the PR number so the only option is to use the commit sha and comment on that commit. I also feel it has value to comment the run result on the commit to connect the run and the log.

This being said, it is my experience that commenting on a commit will be displayed in the pull request view. For example all the commit comments on this PR: #159

**Comment by camposcristianeze** [comment]
That makes sense.. The thing is that comments are only appearing only in merges that I can't figure out where they are coming from. 
![image](https://user-images.githubusercontent.com/1928706/80161312-f41b2200-859d-11ea-8996-bda554683d62.png)

🤔 Maybe because we set this for:
```
on:
  pull_request:
    branches:
      - staging
      - master
```

instead of

```
on: [push]
```

I'll have a look and let you know!
