### ISSUE TITLE
Create docker image

### ISSUE THREAD

**Issue by mitchellsimoens** [ModusCreateOrg/gimbal#47]
Right now for CircleCI, I had to have this jobs config:

```yaml
  gimbal:
    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache: *restore-dist-cache

      - run:
          name: Setup npm
          command: |
            printf "@modus:registry=https://npm.modus.app\n//npm.modus.app/:_authToken=\"%s\"" "$MODUS_NPM_TOKEN" >> ~/.npmrc
            npm set prefix=/home/circleci/npm
            echo 'export PATH=/home/circleci/npm/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install Gimbal
          command: npm install -g @modus/gimbal

      - run:
          name: Run Gimbal
          command: |
            source $BASH_ENV
            gimbal
```

There are some important pieces here. First, the docker image is CircleCI's node image which runs under the `circleci` user. This user does have sudo privilege but where npm wants to default install global modules, the user does not have permission for so sudo is required. TO not do that, I changed where npm installs modules to which caused some sourcing too. Also for puppeteer, I had to use the `:latest-browsers` docker tagged image even though puppeteer installs it's own chrome, it just has some other things installed that is needed at the OS level.

Suffice to say, I think we can make this much easier to to use and a custom docker image may be something we want to use.
